/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'getting-started/index',
    {
      type: 'category',
      label: '认识潮汐栈',
      collapsed: false,
      items: ['overview', 'getting-started/roles-and-scenarios'],
    },
    {
      type: 'category',
      label: '开始搭建',
      collapsed: false,
      items: [
        'getting-started/environment-setup',
        'getting-started/install-develop-platform',
        'getting-started/create-first-application',
        'getting-started/first-business-feature',
      ],
    },
  ],
  lowCodeSidebar: [
    'low-code/index',
    {
      type: 'category',
      label: '总览',
      collapsed: false,
      items: [
        'low-code/overview',
        'low-code/from-requirement-to-delivery',
        'low-code/organization-permissions-configuration-and-notification',
        'low-code/workflow-rules-and-automation',
        'low-code/page-delivery-with-dynamic-forms-and-ui-schema',
        'low-code/forms-attachments-and-documents',
      ],
    },
    {
      type: 'category',
      label: '核心流程',
      collapsed: false,
      items: [
        'guide/tutorial/apps/index',
        'guide/tutorial/business-model/index',
        'guide/tutorial/business-model/develop-business-model/index',
        'guide/tutorial/arrange-modules/index',
      ],
    },
    {
      type: 'category',
      label: '平台能力',
      collapsed: false,
      items: [
        'guide/module/approval-workflow/index',
        'guide/module/organization/index',
        'guide/module/rbac/index',
        'guide/tutorial/dict/index',
        'guide/tutorial/configuration/index',
        'guide/tutorial/notification/index',
        'guide/tutorial/logicflow/index',
        'guide/tutorial/expression/index',
        'guide/tutorial/script/index',
      ],
    },
  ],
  fusionDevelopmentSidebar: [
    'fusion-development/index',
    {
      type: 'category',
      label: '总览与协同',
      collapsed: false,
      items: [
        'fusion-development/overview',
        'fusion-development/when-to-use-code',
        'fusion-development/extension-points',
        'fusion-development/integration-automation-and-realtime',
        'fusion-development/workbench-widgets-and-component-libraries',
        'fusion-development/frontend-extension-paths',
        'fusion-development/custom-login-page-and-auth-integration',
        'fusion-development/backend-extension-packages',
        'fusion-development/development-module-scaffold-and-maven-skeleton',
        'fusion-development/development-platform-support-capabilities',
        'fusion-development/authority-subject-and-access-control-design',
        'fusion-development/high-low-code-collaboration',
        'guide/advance/index',
        'guide/advance/extend-frontend/application-transformation',
        'guide/advance/authority-and-access-control',
      ],
    },
    {
      type: 'category',
      label: '前端扩展',
      link: {
        type: 'doc',
        id: 'guide/advance/extend-frontend/index',
      },
      items: [
        'guide/advance/extend-frontend/micro-app/index',
        'guide/advance/extend-frontend/micro-app/custom-login-integration',
        'guide/advance/extend-frontend/layout-component/index',
        'guide/advance/extend-frontend/amis-component/index',
      ],
    },
    {
      type: 'category',
      label: '后端扩展',
      link: {
        type: 'doc',
        id: 'guide/advance/extend-backend/index',
      },
      items: [
        'guide/advance/extend-backend/extend-field/index',
        'guide/advance/extend-backend/extend-expression/index',
        'guide/advance/extend-backend/extend-script/index',
        'guide/advance/extend-backend/extend-logicflow/index',
      ],
    },
  ],
  operationsSidebar: [
    'operations/index',
    {
      type: 'category',
      label: '运维主题',
      collapsed: false,
      items: [
        'operations/overview',
        'operations/runtime-capability-maintenance',
        'operations/task-message-and-realtime-link-maintenance',
        'operations/business-logs-and-audit-traceability',
        'operations/deployment-architecture',
        'operations/environment-requirements',
        'operations/installation-and-initialization',
        'operations/release-upgrade-and-rollback',
        'operations/backup-monitoring-and-troubleshooting',
      ],
    },
  ],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  referenceSidebar: [
    'reference/index',
    'reference/platform-capability-map',
    { type: 'autogenerated', dirName: 'api' },
    {
      type: 'category',
      label: '常见问题',
      collapsed: false,
      items: ['faq/index', 'faq/backend', 'faq/frontend', 'faq/operations'],
    },
  ],
}

export default sidebars
